apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pms-database
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: pms-database
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dev/pms/database
