apiVersion: v1
kind: ServiceAccount

metadata:
  name: pms-backend
  namespace: default
  annotations:
    # Terraform의 aws_iam_role.pms_backend가 생성할 예정인 Role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::897729143656:role/dev-eks-pms-backend-s3-reader
