CREATE TABLE download_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requested_by VARCHAR(255) NOT NULL,
    customer VARCHAR(255) NOT NULL,
    patch_key VARCHAR(1024) NOT NULL,
    status VARCHAR(32) NOT NULL,
    requested_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    approved_at TIMESTAMP(6) WITH TIME ZONE,
    approved_by VARCHAR(255),
    downloaded_at TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX idx_download_requests_requested_by_requested_at
    ON download_requests (requested_by, requested_at DESC);

CREATE INDEX idx_download_requests_status_requested_at
    ON download_requests (status, requested_at DESC);
